// <auto-generated />
using System;
using Flink.Infraestructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flink.Infraestructure.Migrations
{
    [DbContext(typeof(FlinkContext))]
    [Migration("20220808213806_AddColumnPortadaCursos")]
    partial class AddColumnPortadaCursos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Flink.Infraestructure.Persistance.Curso", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"), 1L, 1);

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<TimeSpan>("Duracion")
                        .HasColumnType("time");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Portada")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TipoCurso")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UrlCurso")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Codigo")
                        .HasName("PK__Curso__06370DADDBF088D6");

                    b.ToTable("Curso", (string)null);

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Categoria = "Desarrollo de software",
                            Descripcion = "Conoce los conceptos clave del lenguaje de programación que se está comiendo al mundo. Aprende qué es una variable, una función, un objeto y dónde se guardan esos valores. Descubre qué es Scope y cómo se utilizan los loops.",
                            Duracion = new TimeSpan(0, 10, 0, 40, 0),
                            Fecha = new DateTime(2022, 8, 8, 16, 38, 6, 49, DateTimeKind.Local).AddTicks(9398),
                            NombreCurso = "Curso de JavaScript",
                            Portada = "https://i.ytimg.com/vi/RqQ1d1qEWlE/maxresdefault.jpg",
                            TipoCurso = "Programacion",
                            UrlCurso = "https://www.youtube.com/watch?v=z95mZVUcJ-E"
                        },
                        new
                        {
                            Codigo = 2,
                            Categoria = "Desarrollo de software",
                            Descripcion = "Aprende Python 3 como un profesional empezando por las bases hasta programar tus propios algoritmos o juegos completos",
                            Duracion = new TimeSpan(0, 9, 8, 40, 0),
                            Fecha = new DateTime(2022, 8, 8, 16, 38, 6, 49, DateTimeKind.Local).AddTicks(9410),
                            NombreCurso = "Curso de Python",
                            Portada = "https://assets2-programarya-com.juandmegon.com/img/Cursos/Python/Python-header.png",
                            TipoCurso = "Programacion",
                            UrlCurso = "https://www.youtube.com/watch?v=swdcD6OPMlk"
                        },
                        new
                        {
                            Codigo = 3,
                            Categoria = "Desarrollo de software",
                            Descripcion = "¡Aprende PHP, el lenguaje de programación para backend presente en el 80% de sitios web! Inicia tu ruta de aprendizaje como PHP Developer y desarrolla tus primeros algoritmos con tu profesor Retax Master.",
                            Duracion = new TimeSpan(0, 7, 29, 40, 0),
                            Fecha = new DateTime(2022, 8, 8, 16, 38, 6, 49, DateTimeKind.Local).AddTicks(9411),
                            NombreCurso = "Curso de PHP",
                            Portada = "https://i0.wp.com/unaaldia.hispasec.com/wp-content/uploads/2019/09/Captura-de-pantalla-de-2019-09-07-04-06-35.png?fit=983%2C633&ssl=1",
                            TipoCurso = "Programacion",
                            UrlCurso = "https://www.youtube.com/watch?v=nCB1gEkRZ1g"
                        },
                        new
                        {
                            Codigo = 4,
                            Categoria = "Desarrollo de software",
                            Descripcion = "Avanza tu camino en el mundo de la programación con C#, uno de los lenguajes más utilizados en desarrollo web y videojuegos, con tu profesor Ricardo Celis.",
                            Duracion = new TimeSpan(0, 6, 29, 40, 0),
                            Fecha = new DateTime(2022, 8, 8, 16, 38, 6, 49, DateTimeKind.Local).AddTicks(9413),
                            NombreCurso = "Curso de C#",
                            Portada = "https://cdn.fs.teachablecdn.com/f0o2YGKTFONup7nJc8aQ",
                            TipoCurso = "Programacion",
                            UrlCurso = "https://www.youtube.com/watch?v=TqiysLEBZo4"
                        });
                });

            modelBuilder.Entity("Flink.Infraestructure.Persistance.LoginUsuario", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdmin"), 1L, 1);

                    b.Property<bool>("Activo")
                        .IsUnicode(false)
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdAdmin")
                        .HasName("PK__LoginUsuario__");

                    b.ToTable("LoginUsuario", (string)null);
                });

            modelBuilder.Entity("Flink.Infraestructure.Persistance.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Apellido2")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("contraseña");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre2")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF97EF70E641");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Apellido1 = "Restrepo",
                            Contraseña = "123456",
                            Correo = "fraiden@Gmail.com",
                            Nombre1 = "Fraiden",
                            NombreUsuario = "LOL"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Apellido1 = "lol",
                            Contraseña = "1234567855",
                            Correo = "cris@Gmail.com",
                            Nombre1 = "Chirs",
                            NombreUsuario = "im"
                        },
                        new
                        {
                            IdUsuario = 3,
                            Apellido1 = "Venites",
                            Contraseña = "1414",
                            Correo = "Holi@Gmail.com",
                            Nombre1 = "Andres",
                            NombreUsuario = "elmatalocos"
                        },
                        new
                        {
                            IdUsuario = 4,
                            Apellido1 = "nedaños",
                            Contraseña = "1313131",
                            Correo = "nada@Gmail.com",
                            Nombre1 = "lolito",
                            NombreUsuario = "LOL"
                        });
                });

            modelBuilder.Entity("Flink.Infraestructure.Persistance.UsuarioCurso", b =>
                {
                    b.Property<int>("UsuarioCursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioCursoId"), 1L, 1);

                    b.Property<int?>("CodigoCurso")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("UsuarioCursoId");

                    b.HasIndex("CodigoCurso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuarioCurso", (string)null);
                });

            modelBuilder.Entity("Flink.Infraestructure.Persistance.UsuarioCurso", b =>
                {
                    b.HasOne("Flink.Infraestructure.Persistance.Curso", "Codigo")
                        .WithMany("UsuarioCursos")
                        .HasForeignKey("CodigoCurso")
                        .HasConstraintName("FK__UsuarioCu__Codig__3B75D760");

                    b.HasOne("Flink.Infraestructure.Persistance.Usuario", "UsuarioId")
                        .WithMany("UsuarioCursos")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__UsuarioCu__IdUsu__3A81B327");

                    b.Navigation("Codigo");

                    b.Navigation("UsuarioId");
                });

            modelBuilder.Entity("Flink.Infraestructure.Persistance.Curso", b =>
                {
                    b.Navigation("UsuarioCursos");
                });

            modelBuilder.Entity("Flink.Infraestructure.Persistance.Usuario", b =>
                {
                    b.Navigation("UsuarioCursos");
                });
#pragma warning restore 612, 618
        }
    }
}
